flaskr/blog/models.py
from flaskr import db
from datetime import datetime


subs = db.Table('subs',
    db.Column('design_id', db.Integer, db.ForeignKey('design.design_id')),
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.tag_id'))
)


class Design (db.Model):
    design_id = db.Column(db.Integer, primary_key=True)
    design_name = db.Column(db.String(40))
    design_content = db.Column(db.String(200))
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    subscriptions = db.relationship('Tag',
                    secondary=subs,
                    backref = db.backref('subscribers', lazy='dynamic')
        )

    def __repr__(self):
        return '<Design {}>'.format(self.design_id)


class Tag(db.Model):
    tag_id = db.Column(db.Integer, primary_key=True)
    tag_name = db.Column(db.String(20))

    def __repr__(self):
        return '<Tag {}>'.format(self.tag_name)

flaskr/__init__.py
import os
import click
from flask import Flask
from flask.cli import with_appcontext
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap

__version__ = (1, 0, 0, "dev")

db = SQLAlchemy()


def create_app(test_config=None):
    """Create and configure an instance of the Flask application."""
    app = Flask(__name__, instance_relative_config=True)
    Bootstrap(app)
    migrate = Migrate(app, db)
    # some deploy systems set the database url in the environ
    db_url = os.environ.get("DATABASE_URL")

    if db_url is None:
        # default to a sqlite database in the instance folder
        db_url = "sqlite:///" + os.path.join(app.instance_path, "flaskr.sqlite")
        # ensure the instance folder exists
        os.makedirs(app.instance_path, exist_ok=True)

    app.config.from_mapping(
        # default secret that should be overridden in environ or config
        SECRET_KEY=os.environ.get("SECRET_KEY", "dev"),
        SQLALCHEMY_DATABASE_URI=db_url,
        SQLALCHEMY_TRACK_MODIFICATIONS=False,
    )

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile("config.py", silent=True)
    else:
        # load the test config if passed in
        app.config.update(test_config)

    # initialize Flask-SQLAlchemy and the init-db command
    db.init_app(app)
    app.cli.add_command(init_db_command)

    # apply the blueprints to the app
    from flaskr import blog

    app.register_blueprint(blog.bp)

    # make "index" point at "/", which is handled by "blog.index"
    app.add_url_rule("/", endpoint="index")

    return app


def init_db():
    db.drop_all()
    db.create_all()


@click.command("init-db")
@with_appcontext
def init_db_command():
    """Clear existing data and create new tables."""
    init_db()
    click.echo("Initialized the database.")

flaskr/blog/__init__.py
from .views import bp

flaskr/blog/views.py
from flask import Blueprint
from flask import flash
from flask import g
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from werkzeug.exceptions import abort

from flaskr import db
from flaskr.blog.models import Design, Tag

bp: Blueprint = Blueprint("blog", __name__)


@bp.route("/", methods=['POST', 'GET'])
def index():
    if request.method == 'POST':
        tag_id_list = request.form.getlist('mycheckbox')
        filter_posts = set()
        filter_tags = []
        for tag_id in tag_id_list:
            tag = Tag.query.get_or_404(tag_id)
            filter_tags.append(tag)
            for post in tag.subscribers:
                filter_posts.add(post)
        tags = Tag.query.all()
        return render_template("blog/index.html", posts=filter_posts, tags=tags, filtered_tags=filter_tags)
    else:
        posts = Design.query.all()
        tags = Tag.query.all()
        return render_template("blog/index.html", posts=posts, tags=tags)


@bp.route('/delete/<int:id>')
def delete(id):
    design_to_delete = Design.query.get_or_404(id)

    for each_tag in design_to_delete.subscriptions:
        # All the tags in that design
        designs_using_tag = []
        for any_design in each_tag.subscribers:
            #Designs that use that tag
            designs_using_tag.append(any_design.design_name)
        if len(designs_using_tag) == 1:
            try:
                db.session.delete(each_tag)
            except:
                return 'There was a problem deleting the tag from task'

    try:
        db.session.delete(design_to_delete)
        db.session.commit()
        return redirect(url_for("blog.index"))
    except:
        return 'There was a problem deleting that task'


@bp.route('/update/<int:id>', methods=['GET', 'POST'])
def update(id):
    post = Design.query.get_or_404(id)
    tag_string = ""
    orignal_tags = set()
    for design_tag in post.subscriptions:
        tag_string += design_tag.tag_name + ","
        orignal_tags.add(design_tag.tag_name)
    if request.method == 'POST':
        post.design_content = request.form['content']
        post.design_name = request.form['name']
        tag_content = request.form['tag_input']

        multi_tags = tag_content.split(',')
        for each_tag in multi_tags:
            #Add new tag
            if each_tag not in orignal_tags:
                #add the tag to the design
                exists = Tag.query.filter_by(tag_name=each_tag).first()
                if exists is not None:
                    # return 'This Tag is Found'
                    post.subscriptions.append(exists)
                else:
                    #Tag has never been used before
                    new_tag = Tag(tag_name=each_tag)
                    db.session.add(new_tag)
                    post.subscriptions.append(new_tag)
            #Removed an existing tag
            else:
                ##Tag is already part of deisgn
                orignal_tags.remove(each_tag)
        if len(orignal_tags) > 0:
            for tag_to_delete in orignal_tags:
                tag_id_to_delete = Tag.query.filter_by(tag_name=tag_to_delete).first()
                post.subscriptions.remove(tag_id_to_delete)
                designs_using_tag = []
                for any_design in tag_id_to_delete.subscribers:
                    designs_using_tag.append(any_design.design_name)
                if len(designs_using_tag) > 0:
                    db.session.delete(tag_id_to_delete)
            #Do nothing
        try:
            db.session.commit()
            return redirect(url_for("blog.index"))
        except:
            return 'There was an error updating task'
    else:
        return render_template("blog/update.html", post=post, tag_string=tag_string)


@bp.route('/search/<int:id>', methods=['GET', 'POST'])
def search(id):
    posts = []
    tag = Tag.query.get_or_404(id)
    for p in tag.subscribers:
        posts.append(p)

    return render_template("blog/index.html", posts=posts)


@bp.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        design_content_input = request.form['design_input']
        tag_content = request.form['tag_input']
        design_info = request.form['design_info']
        new_design = Design(design_name=design_content_input,
                            design_content=design_info)
        if tag_content != "":
            multi_tags = tag_content.split(',')
            for each_tag in multi_tags:
                exists = Tag.query.filter_by(tag_name=each_tag).first()
                if exists is not None:
                    # return 'This Tag is Found'
                    new_design.subscriptions.append(exists)
                else:
                    new_tag = Tag(tag_name=each_tag)
                    db.session.add(new_tag)
                    new_design.subscriptions.append(new_tag)

        try:
            db.session.add(new_design)
            db.session.commit()
            return redirect(url_for('blog.index'))
        except:
            return "There was a problem adding new designs"
    else:
        return render_template("blog/create.html")

flaskr/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}"-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.css" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.min.js" crossorigin="anonymous"></script>

</head>
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand align-left" href="{{ url_for('blog.index') }}">
    <img src="https://img.icons8.com/cute-clipart/64/000000/home.png" width="30" height="30" style= "float:left" class="d-inline-block align-top" alt="">
  </a>
  <a class="navbar-brand" href="{{ url_for('blog.create') }}">
    <img src="https://img.icons8.com/cotton/64/000000/add--v2.png" width="30" height="30" class="d-inline-block align-top" alt="">
  </a>
</nav>


{% block body %}{% endblock %}
</html>

flaskr/templates/blog/create.html
{% extends 'base.html' %}

{% block body %}
<div class="container center-div">
    <h1>Submit New Design</h1>
</div>



<form class="was-validated" action="/create" method="POST">
<div class="container center_div mb-3">
  <label for="design_input">Design Title</label>
  <input type="text" class="form-control is-invalid" name="design_input" id="design_input" placeholder="Title" required>
  <!--<div class="invalid-feedback">-->
    <!--Please provide a title.-->
  <!--</div>-->
  <br>


  <label for="design_info">Design Title</label>
  <textarea class="form-control is-invalid" name="design_info" id="design_info" placeholder="Some info about design" rows="3" required></textarea>
  <!--<div class="invalid-feedback">-->
    <!--Please provide some details about the design.-->
  <!--</div>-->
  <br>



  <label for="tag_input">Tags</label>
  <input type="text" class="form-control col-sm-12" value="" data-role="tagsinput" name="tag_input" id="tag_input" placeholder="Tags">
  <br>
  <br>

  <button class="btn btn-primary" type="submit">
      Submit Design
  </button>
</div>

</form>


{% endblock %}

flaskr/templates/blog/index.html
{% extends 'base.html' %}

<!--{% block head %}-->

<!--{% endblock %}-->

{% block body %}
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidebar {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 62px;
  left: 0;
  side: 10px;
  background-color: white;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 20px;
}

#sidebaritems {
  padding: 8px 8px 8px 52px;
  text-decoration: none;
  font-size: 15px;
  color: black;
  display: block;
  transition: 0.3s;
}

.sidebar .closebtn {
  position: absolute;
  top: 0;
  right: 25px;
  font-size: 36px;
  margin-left: 50px;
}

.openbtn {
  font-size: 20px;
  cursor: pointer;
  background-color: white;
  color: black;
  padding: 10px 10px;
  border: none;
}

.openbtn:hover {
  background-color: white;
}

#main {
  transition: margin-left .5s;
  padding: 10px;

}

/* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
@media screen and (max-height: 450px) {
  .sidebar {padding-top: 15px;}
  .sidebar a {font-size: 18px;}
}
</style>

{% if not posts %}
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h2>Looks like there is nothing added, why don't you add some.</h2>
  </div>
</div>
{% endif %}

{% if filtered_tags %}
<div class="row">
  <div class="col-md-6 offset-md-3">
    <td>Filtered by:   </td>
    {% for tags in filtered_tags %}
      <span class="badge badge-secondary">{{ tags.tag_name }}</span>
    {% endfor %}
  </div>
</div>
{% endif %}

<div id="mySidebar" class="sidebar">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
    <div id="sidebaritems">
      <h1>Tags</h1>
      <form method="POST" action="/">
      {% for tag in tags %}
        <input type="checkbox" value="{{tag.tag_id}}" name="mycheckbox">  {{tag.tag_name }} <br>
      {% endfor %}
        <br>
      <input type="submit" value="Filter">
      </form>
    </div>
</div>

<div id="main">
  <button class="openbtn" onclick="openNav()">☰ Filter</button>
</div>

<script>
function openNav() {
  document.getElementById("mySidebar").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
  document.getElementById("mySidebar").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
</script>

<div class="row">
  <div class="col-8 container center_div">
    <div class="row">
      {% for post in posts %}
        <div class="col-sm-4">
          <div class="card w-20">
            <div class="card-body">
              <h5 class="card-title">{{ post.design_name }}</h5>
              <p class="card-text">{{ post.design_content }}</p>
              <br>
              {% for designTag in post.subscriptions %}
                <a href="/search/{{ designTag.tag_id }}" class="btn btn-primary btn-sm">{{ designTag.tag_name }}</a>
              {% endfor %}

          </div>
          <div class="card-footer">
            <small class="text-muted">
              <a class="card-link" href="/delete/{{post.design_id}}">Delete</a>
              <a class="card-link" href="/update/{{post.design_id}}">Update</a>
            </small>
          </div>
          </div>
          <br>
        </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

flaskr/templates/blog/update.html
{% extends 'base.html' %}

{% block body %}

<div class = "container center-div">
    <h1>Edit Design</h1>
</div>

<form class="was-validated" action="/update/{{post.design_id}}" method="POST">
<div class="container center_div mb-3">

  <label for="design_input">Design Title</label>
  <input type="text" class="form-control is-invalid" name="name" id="name" value="{{post.design_name}}" required>
  <!--<div class="invalid-feedback">-->
    <!--Please provide a title.-->
  <!--</div>-->
  <br>


  <label for="design_info">Design Title</label>
      <textarea class="form-control is-invalid" name="content" id="content" rows="3" required>{{post.design_content}}</textarea>
  <!--<div class="invalid-feedback">-->
    <!--Please provide some details about the design.-->
  <!--</div>-->
  <br>


  <label for="tag_input">Tags</label>
  <input type="text" class="form-control col-sm-12" data-role="tagsinput" name="tag_input" id="tag_input" value="{{tag_string}}">
  <br>
  <br>

  <button class="btn btn-primary" type="submit">
      Edit Design
  </button>
</div>

</form>
{% endblock %}